theme = "custom-onedark"

[editor]
line-number = "relative"
true-color = true
lsp.display-inlay-hints = true
mouse = false

[keys.insert]
"C-[" = ["normal_mode"]

[keys.select]
"C-[" = ["normal_mode"]
